[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  # Environment variables (if needed)
  NODE_VERSION = "18"

[[redirects]]
  # Redirect root to main page
  from = "/"
  to = "/html/main.html"
  status = 200

[[redirects]]
  # Handle 404s by redirecting to main page
  from = "/*"
  to = "/html/main.html"
  status = 404

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://notknown.app.n8n.cloud; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self' https://notknown.app.n8n.cloud;"

[[headers]]
  # Cache static assets
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/plugins/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Form handling (if you add contact forms later)
# [[redirects]]
#   from = "/contact"
#   to = "/.netlify/functions/contact"
#   status = 200